services:
  - type: web
    name: mortalidad-colombia-2019
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.app:app
    envVars:
      - key: PORT
        value: 8080
